image_segmentation:
  ros__parameters:
    update_rate: 60.0

    rgb_topic: "/k4a/rgb/image_raw"
    depth_topic: "/k4a/depth_to_rgb/image_raw"

    hsv_hue_low: 0
    hsv_hue_high: 179
    hsv_saturation_low: 0
    hsv_saturation_high: 255
    hsv_value_low: 0
    hsv_value_high: 100

    depth_low: 0
    depth_high: 2000
    depth_scale: 1.0

    connectivity: 4

    min_component_area: 150000
    max_component_area: 200000
    keep_multiple_components: False

    gaussian_kernel_size_width: 5
    gaussian_kernel_size_height: 5
    gaussian_sigma: 5.0

    hsv_morph_kernel_size_width: 3
    hsv_morph_kernel_size_height: 3
    hsv_morph_erode_iterations: 3
    hsv_morph_dilate_iterations: 5

    depth_morph_kernel_size_width: 3
    depth_morph_kernel_size_height: 3
    depth_morph_erode_iterations: 8
    depth_morph_dilate_iterations: 8

yolov8_segmentation:
  ros__parameters:
    update_rate: 20.0

    rgb_topic: '/k4a/rgb/image_raw'
    depth_topic: '/k4a/depth_to_rgb/image_raw'
    
    confidence_threshold: 0.5

    depth_low: 0
    depth_high: 2000
    depth_scale: 1.0

    connectivity: 4

    min_component_area: 150000
    max_component_area: 200000
    keep_multiple_components: False

    gaussian_kernel_size_width: 5
    gaussian_kernel_size_height: 5
    gaussian_sigma: 5.0

    yolo_morph_kernel_size_width: 3
    yolo_morph_kernel_size_height: 3
    yolo_morph_erode_iterations: 2
    yolo_morph_dilate_iterations: 2

    depth_morph_kernel_size_width: 3
    depth_morph_kernel_size_height: 3
    depth_morph_erode_iterations: 8
    depth_morph_dilate_iterations: 8

point_cloud_generator:
  ros__parameters:
    update_rate: 10.0

    depth_scale: 1000.0                 
    voxel_size: 0.002                    

    tf_x: 0.027
    tf_y: 0.033
    tf_z: 0.137
    tf_qx: 0.0
    tf_qy: 0.0
    tf_qz: 0.0
    tf_qw: 1.0

point_cloud_scaling:
  ros__parameters:
    update_rate: 10.0
    
    scaling_mode: 'largest_dim'